;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/ArcadeGameSong.aks
;;;; Generation time: mar 26 oct 2021 22:46:09 CEST
;;;;

;;;; Song 'GameSong' metadata constants
GameSong_address = 0x40
GameSong_size    = 160
GameSong_end     = 0xdf

;;;; Song 'GameSong' declaration
.globl _GameSong
