;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/ArcadeGameSong.aks
;;;; Generation time: vie 29 oct 2021 23:27:55 CEST
;;;;

;;;; Song 'gameSong' metadata constants
gameSong_address = 0x40
gameSong_size    = 160
gameSong_end     = 0xdf

;;;; Song 'gameSong' declaration
.globl _gameSong
