;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: assets/auxSong.aks
;;;; Generation time: mar 26 oct 2021 16:59:50 CEST
;;;;

;;;; Song 'gameSong' metadata constants
gameSong_address = 0x40
gameSong_size    = 106
gameSong_end     = 0xa9

;;;; Song 'gameSong' declaration
.globl _gameSong
